#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx='startx $XINITRC'

[ -f "$MBSYNCRC" ] && alias mbsync='mbsync -c $MBSYNCRC'

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

se() {
	s=("${HOME}/.local/bin/"**/*(.))
	c="$(print -lnr ${s:t:r} | fzf)"
	[[ "${c}" ]] && "${EDITOR}" ${${(M)s:#*/${c}*}[1]}
}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	rs="/usr/lib/rstudio/rstudio" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e='$EDITOR' \
	v='$EDITOR' \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
        of="sudo openfortivpn -c /etc/openfortivpn/myconfig" \
        am="sudo mount -a" \
        da="xfreerdp /multimon /f /u:perry.rusken@da.nl /v:172.16.110.81" \
        sb="WEBKIT_DISABLE_COMPOSITING_MODE=1 surf" \
	z="zathura"

alias \
	lf="lfub" \
	sf="sudo lf" \
	magit="nvim -c MagitOnly" \
	hlf="nvim /home/perrob/Documenten/helpLF" \
	ref='shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutenvrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc'
